### ISSUE TITLE
Not compatible with the latest version of PyCharm CE

### ISSUE THREAD

**Issue by rbf911** [aymanosman/intellij-racket#11]
Trying to add the plugin and there is a compatibility issue.
PyCharm info.:

PyCharm 2023.2 (Community Edition)
Build #PC-232.8660.197, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.chesterccw.excelreader (2023.6.1-222.232)
    com.intellij.ideolog (222.1.0.0)
    com.intellij.plugin.adernov.powershell (2.0.10)
    org.rust.lang (0.4.200.5421-232)
    nl.rubensten.texifyidea (0.9.1)
    com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.15.0)

**Comment by aymanosman** [comment]
I've published a new version which will work for PyCharm Community — 2021.3 — 2023.2.1. It is pending approval (version 0.0.15).

I will close this issue when it is approved.

**Comment by aymanosman** [comment]
The plugin has been approved.
