### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2024.3.1.1)

### ISSUE THREAD

**Issue by jtaub** [aymanosman/intellij-racket#16]
Unfortunately this plugin isn't compatible with any recent version of Intellij.

I have not developed an Intellij plugin before, but if someone could point me in the right direction, I would be happy to attempt to fix this myself.

![image](https://github.com/user-attachments/assets/960db99d-969d-4d61-94b6-bbd70dbd9a93)

**Comment by aymanosman** [comment]
Just published a new version.

It requires minimal changes on my side to expand the compatibility range, but it is manual.

There is a way to leave the end range open, but I'm not sure if that is a good thing. Open to suggestions.
