### ISSUE TITLE
Plugin compatibility

### ISSUE THREAD

**Issue by filiplajszczak** [aymanosman/intellij-racket#2]
Is there a serious reason to limit the plugin compatibility to IntelliJ IDEA & Android Studio only?

**Comment by aymanosman** [comment]
Sorry I didn't see this. It seems I wasn't subscribed to notifications on this repository!

No, there is no reason for this.

Am I right in believing that all I have to do is remove [this](https://github.com/aymanosman/intellij-racket/blob/master/src/main/resources/META-INF/plugin.xml#L9) line?

**Comment by aymanosman** [comment]
[fixed](https://github.com/aymanosman/intellij-racket/commit/727134dc1526c7f2ba9759a2b6d18c171715772c) and [released](https://plugins.jetbrains.com/plugin/14752-racket/versions/stable/101120)
