### ISSUE TITLE
not found in 2021.2.1

### ISSUE THREAD

**Issue by dannypsnl** [aymanosman/intellij-racket#3]

**Comment by aymanosman** [comment]
I'm currently waiting on [this PR](https://github.com/JetBrains/intellij-platform-plugin-template/pull/138) to wrap up so I know what I have to do to get this plugin to work on the new IntelliJ release.

**Comment by aymanosman** [comment]
Managed to integrate the code from that PR and publish a new version of the plugin (0.0.11) that is just awaiting approval.

I'll close the issue once it passes review.

**Comment by aymanosman** [comment]
It's on the marketplace!
