### ISSUE TITLE
Not compatible with the latest version (Intellij IDEA 2022.2.2)

### ISSUE THREAD

**Issue by SBOne-Kenobi** [aymanosman/intellij-racket#5]
Racket plugin for Intellij is not supported for the latest version of IDE. There is no way to install the plugin 😢

**Comment by aymanosman** [comment]
I've published a new version which works on newer versions of Intellij IDEA. It is pending approval (version 0.0.12).

**Comment by aymanosman** [comment]
@SBOne-Kenobi, plugin has been approved. It should be ready to download.
